config/routes.rb
Rails.application.routes.draw do

  get 'users/show'

  get 'users/update'

  resources :charges, only: [:new, :create]

  resources :wikis do
    resources :collaborations
  end

  devise_for :users
  resources :users, only: [:update]
  get 'about' => 'welcome#about'

  root 'welcome#index'

end

app/models/collaboration.rb
class Collaboration < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :wikis
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 # after_create :set_default_role

  def standard?
    self.role == 'standard'
  end

  def premium?
    self.role == 'premium'
  end

  def admin?
    self.role == 'admin'
  end

  private

  def set_default_role
    self.role = 'standard'
    self.save!
  end
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborations
  has_many :users, through: :collaborations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "Premium Membership - #{current_user.email}",
      amount: 1500
    }
  end  

  def create
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )
  
    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: 1500,
      description: "Premium Membership - #{current_user.email}",
      currency: 'usd'
    )
  
    flash[:notice] = "Transaction approved, #{current_user.email}!"
    current_user.update_attribute(:role, "premium")
    current_user.save!
    redirect_to wikis_path
  
    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to new_charge_path
  end
end

app/controllers/collaborations_controller.rb
class CollaborationsController < ApplicationController
  def new
    @wiki = Wiki.find(params[:wiki_id])
    if @wiki.collaborations.nil?
      @users = User.where.not(id: current_user.id)
    else
      @users = []
      users_list = User.where.not(id: current_user.id)
      collaborators_user_id_list = @wiki.collaborations.pluck(:user_id)
      users_list.each do |user|
        if !collaborators_user_id_list.include?(user.id)
          @users << user
        end
      end
    end
    @collaboration = @wiki.collaborations.new
  end

  def create
    @wiki = Wiki.find(params[:wiki_id])
    @collaboration = @wiki.collaborations.build(collaboration_params)
    @collaboration.save!
    redirect_to @wiki
  end

  def destroy
    @collaboration = Collaboration.find(params[:id])
    @wiki = Wiki.find_by(id: @collaboration.wiki_id)
    @collaboration.destroy
    redirect_to @wiki
  end

  private

  def collaboration_params
    params.require(:collaboration).permit(:user_id, :wiki_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end

  def update
    @user = User.find(params[:id] || current_user)
    @user.role = "standard"
    @user.save!

    self.make_private_wikis_public

    redirect_to wikis_path
  end

  def make_private_wikis_public
    user_wikis = Wiki.where(user_id: current_user.id)
    user_wikis.each do |wiki|
      wiki.private = false
      wiki.save!
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
    before_action :authorize_user, except: [:index, :new, :create]

  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user

    if @wiki.save
      flash[:notice] = "Wiki was created successfully."
      redirect_to(@wiki)
    else
      flash.now[:alert] = "Error creating wiki.  Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.assign_attributes(wiki_params)

    if @wiki.save
      flash[:notice] = "Wiki was updated successfully."
      redirect_to(@wiki)
    else
      flash.now[:alert] = "Error updating wiki.  Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to action: :index
    else
      flash.now[:alert] = "Error deleting the wiki. Please try again."
      render :show
    end
  end

  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end

  def authorize_user
    @wiki = Wiki.find(params[:id])
    if @wiki.private?
      redirect_to(action: :index) unless current_user == @wiki.user || current_user.admin? || @wiki.collaborations.pluck(:user_id).include?(current_user.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %><br>
  <h4>Click this button to upgrade to premium!</h4>
  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> data-description="<%= @stripe_btn_data[:description] %>" ></script>
  <h4>Click this button to downgrade to standard. Your private wikis will become public.</h4>
  <%= link_to "Downgrade", users_update_path(current_user), class: 'btn seahawk', data: { confirm: 'All private wikis will become public. Are you sure you want to downgrade?'  } %>
<% end %>

app/views/collaborations/_form.html.erb
<%= form_for([@wiki, @collaboration]) do |f| %>
  <div class="field">
    <%= f.select 'user_id', options_for_select(@users.collect{ |u| [u.email, u.id] }) %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/collaborations/new.html.erb
<h1>Add collaborator</h1>

<%= render 'form' %>

<br>

<h2>Current Collaborators</h2>
<% existing_collaboration_user_id_array = @wiki.collaborations.pluck(:user_id) %>
<% existing_collaboration_user_id_array.each do |id| %>
  <% user_to_display = User.find_by(id: id) %>
  <% collaboration = Collaboration.find_by(user_id: user_to_display.id) %>
  <h4><%= user_to_display.email %></h4>
  <%= link_to "Remove Collaborator", wiki_collaboration_path(@wiki, collaboration.id), method: :delete, class: 'btn reverse' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Blocipedia", root_path %></li>
      <li><%= link_to "Wikis", wikis_path %></li>
      <li><%= link_to "About", about_path %></li>
      <div class="pull-right user-info">
        <% if user_signed_in? %>
          Signed in as: <strong><%= current_user.email %></strong> |
          Membership: <%= link_to 'WTF', new_charge_path, class: 'navbar-link' %> |
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
          <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </div>
    </ul>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash.now[:alert] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash.now[:alert] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
  </div>

</body>
</html>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/welcome/about.html.erb
<h1>About Blocipedia</h1>
<h3>Created by: jd king</h3>

app/views/welcome/index.html.erb
<h1>Welcome to Blocipedia.</h1>
<h3>A Wiki Collaboration Community</h3>

app/views/wikis/_form.html.erb
<%= form_for @wiki do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>

  <%= f.label :body %>
  <%= f.text_area :body, class: 'form-control' %><br>

  <% if @wiki.id.nil? %>
    <% if current_user.premium? || current_user.admin? %>
      <div class="form_group">
        <%= f.label :private, class: 'checkbox' do %>
          <%= f.check_box :private %> Private topic
        <% end %>
      </div>
    <% end %>
  <% else %>
    <% if current_user == @wiki.user || current_user.admin? %>
      <div class="form_group">
        <%= f.label :private, class: 'checkbox' do %>
          <%= f.check_box :private %> Private topic
        <% end %>
      </div>
    <% end %>
  <% end %>

  <%= f.submit "Save", class: 'btn seahawk'%>
<% end %>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<div class="row">
  <div class="col-md-8">
    <%= render partial: 'form', locals: { wiki: @wiki } %>
  </div>
</div>
<br>
<% if @wiki.user == current_user %>
  <div class="row">
    <div class="col-md-1">
      <%= link_to "Collaborators", new_wiki_collaboration_path(@wiki), class: 'btn reverse' %>
    </div>
  </div>
<% end %>

app/views/wikis/index.html.erb
<h1>Wikis</h1>
<br>
<div class="row">
  <div class="col-md-8">
    <% @wikis.each do |wiki| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to wiki.title, wiki %>
          </h4>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-4">
    <div class="col-md-4">
      <%= link_to "New Wiki", new_wiki_path, class: 'btn seahawk' %>
    </div>
  </div>
</div>

app/views/wikis/new.html.erb
<h1>Wiki Creation</h1>

<div class="row">
  <div class="col-md-8">
    <%= render partial: 'form', locals: { wiki: @wiki } %>
  </div>
</div>

app/views/wikis/show.html.erb
<br>
<div class="rom">
  <div class="col-md-1">
    <%= link_to "Edit Wiki", edit_wiki_path, class: 'btn seahawk' %>
  </div>
  <div class="col-md-2">
    <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this topic?'  } %>
  </div>
</div><br><br>
<h1><%= @wiki.title %></h1>
<h3 class="wiki-body"><%= markdown(@wiki.body) %></h3>